spring:
  application:
    name: gestao-projetos

  datasource:
    url: jdbc:postgresql://localhost:5432/GESTAO_PROJETOS
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  spring-doc:
    paths-to-match: /gestao-projetos/**/**
    swagger-ui:
      use-root-path: true

